"""Provider-agnostic ticker universe table.

The `universe` table has one row per instrument (canonical key = Stooq ticker
symbol) with a `yahoo_ticker` column holding the yfinance-compatible symbol.
`yahoo_ticker` is NULL for instruments that have no Yahoo Finance equivalent.

`yahoo_ticker` translation rules applied at build time:
  - currencies, 6-char alpha (e.g. EURUSD)  ->  EURUSD=X
  - currencies, non-standard (NOK_I, EUR_I)  ->  NULL  (Stooq-specific)
  - stooq stocks indices (^_UK, ^_US, ...)   ->  NULL  (Stooq-proprietary)
  - preferred/series shares BASE_X           ->  BASE-PX  (e.g. RNR_F -> RNR-PF)
  - everything else                          ->  same as Ticker

`refresh()` rebuilds the table from the Stooq raw markets.csv.
Trigger via `uv run irp` -> Steps -> universe.

`universe()` is a read-only accessor using the db() singleton, consistent
with irp.data.stooq / irp.data.yahoo / irp.data.catalog.
"""
import logging
import re
from pathlib import Path

import duckdb
import pandas as pd

from irp.core.config import config
from irp.data._common import db, ticker_filter

logger = logging.getLogger(__name__)

_raw_markets_csv = (
    Path(config.data.root_dir) / config.providers.stooq.raw_dir / 'markets.csv'
)


def universe(tickers: str | list[str] | None = None) -> pd.DataFrame:
    """Provider-agnostic ticker universe with per-provider symbols."""
    clause, params = ticker_filter(tickers)
    where = f'WHERE {clause}' if clause else ''
    return db().execute(f'SELECT * FROM universe {where} ORDER BY Ticker', params).df()


def _yahoo_ticker(ticker: str, market: str) -> str | None:
    m = market.lower()
    if m == 'stooq stocks indices':
        return None
    if m == 'currencies':
        if re.fullmatch(r'[A-Z]{6}', ticker):
            return f'{ticker}=X'
        return None
    match = re.fullmatch(r'([A-Z0-9]+)_([A-Z])', ticker)
    if match:
        return f'{match.group(1)}-P{match.group(2)}'
    return ticker


def refresh(markets_csv: Path | None = None) -> int:
    """Rebuild the `universe` table from Stooq's raw markets.csv.

    Reads ticker+market pairs, applies _yahoo_ticker() translation rules to
    populate the yahoo_ticker column, then writes CREATE OR REPLACE TABLE.

    Primary source: data/stooq/raw/markets.csv (generated by StooqSource
    fetch_bulk). Fallback: existing `universe` DB table (useful when the CSV
    was cleaned up but the table still holds the right Ticker+Market data).

    Returns the row count of the rebuilt table.
    """
    csv_path = markets_csv or _raw_markets_csv
    if csv_path.exists():
        raw = pd.read_csv(csv_path)  # columns: ticker, market (lowercase)
        rows = []
        seen: set[str] = set()
        for _, row in raw.iterrows():
            ticker = row['ticker'].upper().split('.')[0]
            if ticker in seen:
                continue
            seen.add(ticker)
            market = row['market']
            rows.append({
                'Ticker': ticker,
                'Market': market,
                'yahoo_ticker': _yahoo_ticker(ticker, market),
            })
        df = pd.DataFrame(rows)
    else:
        logger.info('markets.csv not found, falling back to existing universe table')
        with duckdb.connect(str(config.database.path), read_only=True) as con:
            existing = con.execute('SELECT Ticker, Market FROM universe').df()
        df = existing.assign(
            yahoo_ticker=existing.apply(
                lambda r: _yahoo_ticker(r['Ticker'], r['Market']), axis=1
            )
        )

    with duckdb.connect(config.database.path) as con:
        con.register('_universe_new', df)
        con.execute('CREATE OR REPLACE TABLE universe AS SELECT * FROM _universe_new')
        count: int = con.execute('SELECT COUNT(*) FROM universe').fetchone()[0]  # type: ignore[index]
    return count


def main() -> None:
    import time
    from irp.core.logging import configure_logging
    configure_logging()
    print('Refreshing universe table...')
    t0 = time.perf_counter()
    n = refresh()
    elapsed = time.perf_counter() - t0
    print(f'Done — {n:,} tickers in {elapsed:.1f}s')
    df = universe()
    null_counts = df[df['yahoo_ticker'].isna()].groupby('Market').size()
    if not null_counts.empty:
        print('\nNULL yahoo_ticker by market (no Yahoo equivalent):')
        print(null_counts.to_string())


if __name__ == '__main__':
    main()
