"""Provider-agnostic ticker universe table.

The `universe` table has one row per instrument with four columns:

  Ticker        VARCHAR  — canonical key (Stooq SrcId stripped of exchange suffix)
  Market        VARCHAR  — market category from Stooq zip structure
  stooq_ticker  VARCHAR  — full Stooq source ticker / SrcId (e.g. AAPL.US); NULL if not Stooq-sourced
  yahoo_ticker  VARCHAR  — yfinance symbol (e.g. EURUSD=X); NULL if no Yahoo equivalent

`yahoo_ticker` translation rules (applied at seed time):
  - currencies, 6-char alpha (e.g. EURUSD)  ->  EURUSD=X
  - currencies, non-standard (NOK_I, EUR_I)  ->  NULL  (Stooq-specific)
  - stooq stocks indices (^_UK, ^_US, ...)   ->  NULL  (Stooq-proprietary)
  - preferred/series shares BASE_X           ->  BASE-PX  (e.g. RNR_F -> RNR-PF)
  - everything else                          ->  same as Ticker

Two operations:

`seed()` — reads `data/stooq/raw/markets.csv` (generated by StooqSource fetch_bulk),
  applies translations, writes `data/universe.csv`. Run via `uv run irp` -> Steps -> seed-universe.

`refresh()` — reads `data/universe.csv`, writes the `universe` DB table. The CSV is the
  source of truth; edit it to add/remove tickers or fix translations. If the CSV is absent,
  falls back to the existing DB table. Run via `uv run irp` -> Steps -> universe.

`universe()` is a read-only accessor using the db() singleton, consistent
with irp.data.stooq / irp.data.yahoo / irp.data.catalog.
"""
import logging
import re
from pathlib import Path

import duckdb
import pandas as pd

from irp.core.config import config
from irp.data._common import db, ticker_filter

logger = logging.getLogger(__name__)

_raw_markets_csv = (
    Path(config.data.root_dir) / config.providers.stooq.raw_dir / 'markets.csv'
)
_universe_csv = Path(config.data.root_dir) / 'universe.csv'


def universe(tickers: str | list[str] | None = None) -> pd.DataFrame:
    """Provider-agnostic ticker universe with per-provider symbols."""
    clause, params = ticker_filter(tickers)
    where = f'WHERE {clause}' if clause else ''
    return db().execute(f'SELECT * FROM main.universe {where} ORDER BY Ticker', params).df()


def _yahoo_ticker(ticker: str, market: str) -> str | None:
    m = market.lower()
    if m == 'stooq stocks indices':
        return None
    if m == 'currencies':
        if re.fullmatch(r'[A-Z]{6}', ticker):
            return f'{ticker}=X'
        return None
    match = re.fullmatch(r'([A-Z0-9]+)_([A-Z])', ticker)
    if match:
        return f'{match.group(1)}-P{match.group(2)}'
    return ticker


def _seed_from_stooq(stooq_csv: Path) -> pd.DataFrame:
    """Build universe DataFrame from Stooq markets.csv.

    markets.csv ticker column = f.stem (e.g. AAPL.US from AAPL.US.txt).
    Canonical Ticker = stooq_ticker split on first dot.
    Deduplicates on canonical Ticker (first occurrence wins).
    """
    raw = pd.read_csv(stooq_csv)
    rows: list[dict] = []
    seen: set[str] = set()
    for _, row in raw.iterrows():
        stooq_t = row['ticker'].upper()
        ticker = stooq_t.split('.')[0]
        if ticker in seen:
            continue
        seen.add(ticker)
        market = row['market']
        rows.append({
            'Ticker': ticker,
            'Market': market,
            'stooq_ticker': stooq_t,
            'yahoo_ticker': _yahoo_ticker(ticker, market),
        })
    return pd.DataFrame(rows)


def seed(markets_csv: Path | None = None, universe_csv: Path | None = None) -> int:
    """Rebuild universe.csv from Stooq markets.csv (always overwrites).

    Primary source: data/stooq/raw/markets.csv (generated by StooqSource
    fetch_bulk). Applies _yahoo_ticker() translation rules and preserves the
    full Stooq ticker (e.g. AAPL.US) as stooq_ticker.

    Returns the row count written to universe.csv.
    """
    stooq_csv = markets_csv or _raw_markets_csv
    out_csv = universe_csv or _universe_csv
    if not stooq_csv.exists():
        raise FileNotFoundError(
            f'markets.csv not found at {stooq_csv}. '
            'Run StooqSource fetch_bulk first to generate it.'
        )
    df = _seed_from_stooq(stooq_csv)
    df.to_csv(out_csv, index=False)
    logger.info(f'Wrote {len(df):,} tickers to {out_csv}')
    return len(df)


def refresh(universe_csv: Path | None = None) -> int:
    """Rebuild the `universe` DB table from universe.csv.

    Primary source: data/universe.csv (the editable master file). Read as-is —
    user edits are preserved; translations are NOT re-applied.

    Fallback: existing `universe` DB table (used when universe.csv was cleaned
    up). stooq_ticker is set to NULL in this case since it cannot be recovered
    without the source file.

    Returns the row count of the rebuilt table.
    """
    csv_path = universe_csv or _universe_csv
    if csv_path.exists():
        df = pd.read_csv(csv_path)
    else:
        logger.info('universe.csv not found, falling back to existing universe DB table')
        with duckdb.connect(str(config.database.path), read_only=True) as con:
            existing = con.execute('SELECT Ticker, Market FROM main.universe').df()
        df = existing.assign(
            stooq_ticker=None,
            yahoo_ticker=existing.apply(
                lambda r: _yahoo_ticker(r['Ticker'], r['Market']), axis=1
            ),
        )

    with duckdb.connect(config.database.path) as con:
        con.register('_universe_new', df)
        con.execute('CREATE OR REPLACE TABLE universe AS SELECT * FROM _universe_new')
        count: int = con.execute('SELECT COUNT(*) FROM main.universe').fetchone()[0]  # type: ignore[index]
    return count


def main() -> None:
    import time
    from irp.core.logging import configure_logging
    configure_logging()
    print('Refreshing universe table...')
    t0 = time.perf_counter()
    n = refresh()
    elapsed = time.perf_counter() - t0
    print(f'Done — {n:,} tickers in {elapsed:.1f}s')
    df = universe()
    null_stooq = df['stooq_ticker'].isna().sum()
    null_yahoo = df['yahoo_ticker'].isna().sum()
    if null_stooq:
        print(f'  stooq_ticker NULL: {null_stooq}')
    if null_yahoo:
        print(f'\nNULL yahoo_ticker by market (no Yahoo equivalent):')
        print(df[df['yahoo_ticker'].isna()].groupby('Market').size().to_string())


if __name__ == '__main__':
    main()
